// This file is auto-generated by the WASM build pipeline. Do not edit manually.

using UnityEngine;
using UnityEngine.Events;

public static class UnityEventRegister
{
    public static void Register()
    {
    }
}
