using System;
using System.Collections.Generic;

namespace WasmScripting {
	public static class TypeMap {
		private static readonly Dictionary<int, Type> IdToType = new()
		{
			#region IdToType
            { 0, typeof(global::UnityEngine.Object) },
            { 1, typeof(global::UnityEngine.AnimationClip) },
            { 2, typeof(global::UnityEngine.AnimationCurve) },
            { 3, typeof(global::UnityEngine.Animator) },
            { 4, typeof(global::UnityEngine.AnimatorControllerParameter) },
            { 5, typeof(global::UnityEngine.ArticulationBody) },
            { 6, typeof(global::UnityEngine.ArticulationJacobian) },
            { 7, typeof(global::UnityEngine.AudioBehaviour) },
            { 8, typeof(global::UnityEngine.AudioClip) },
            { 9, typeof(global::UnityEngine.AudioListener) },
            { 10, typeof(global::UnityEngine.AudioSource) },
            { 11, typeof(global::UnityEngine.Avatar) },
            { 12, typeof(global::UnityEngine.Behaviour) },
            { 13, typeof(global::UnityEngine.BoxCollider) },
            { 14, typeof(global::UnityEngine.Camera.CameraCallback) },
            { 15, typeof(global::UnityEngine.Camera) },
            { 16, typeof(global::UnityEngine.CapsuleCollider) },
            { 17, typeof(global::UnityEngine.Collider) },
            { 18, typeof(global::UnityEngine.Collision) },
            { 19, typeof(global::UnityEngine.Component) },
            { 20, typeof(global::UnityEngine.ComputeBuffer) },
            { 21, typeof(global::UnityEngine.ComputeShader) },
            { 22, typeof(global::UnityEngine.Coroutine) },
            { 23, typeof(global::UnityEngine.Cubemap) },
            { 24, typeof(global::UnityEngine.Debug) },
            { 25, typeof(global::UnityEngine.GameObject) },
            { 26, typeof(global::UnityEngine.Graphics) },
            { 27, typeof(global::UnityEngine.GraphicsBuffer) },
            { 28, typeof(global::UnityEngine.HumanBone) },
            { 29, typeof(global::UnityEngine.HumanDescription) },
            { 30, typeof(global::UnityEngine.Input) },
            { 31, typeof(global::UnityEngine.LightProbeProxyVolume) },
            { 32, typeof(global::UnityEngine.Material) },
            { 33, typeof(global::UnityEngine.MaterialPropertyBlock) },
            { 34, typeof(global::UnityEngine.Mesh) },
            { 35, typeof(global::UnityEngine.MeshCollider) },
            { 36, typeof(global::UnityEngine.MeshFilter) },
            { 37, typeof(global::UnityEngine.MeshRenderer) },
            { 38, typeof(global::UnityEngine.MonoBehaviour) },
            { 39, typeof(global::UnityEngine.Motion) },
            { 40, typeof(global::UnityEngine.PhysicMaterial) },
            { 41, typeof(global::UnityEngine.Physics) },
            { 42, typeof(global::UnityEngine.RectTransform) },
            { 43, typeof(global::UnityEngine.ReflectionProbe) },
            { 44, typeof(global::UnityEngine.Renderer) },
            { 45, typeof(global::UnityEngine.RenderParams) },
            { 46, typeof(global::UnityEngine.RenderTargetSetup) },
            { 47, typeof(global::UnityEngine.RenderTexture) },
            { 48, typeof(global::UnityEngine.Rigidbody) },
            { 49, typeof(global::UnityEngine.RuntimeAnimatorController) },
            { 50, typeof(global::UnityEngine.Shader) },
            { 51, typeof(global::UnityEngine.SkeletonBone) },
            { 52, typeof(global::UnityEngine.SkinnedMeshRenderer) },
            { 53, typeof(global::UnityEngine.SphereCollider) },
            { 54, typeof(global::UnityEngine.Texture2D) },
            { 55, typeof(global::UnityEngine.Texture) },
            { 56, typeof(global::UnityEngine.Time) },
            { 57, typeof(global::UnityEngine.Transform) },
            { 58, typeof(global::UnityEngine.YieldInstruction) },
            { 59, typeof(global::UnityEngine.UI.Graphic) },
            { 60, typeof(global::UnityEngine.UI.MaskableGraphic) },
            { 61, typeof(global::UnityEngine.Rendering.CommandBuffer) },
            { 62, typeof(global::UnityEngine.Rendering.GlobalKeyword) },
            { 63, typeof(global::UnityEngine.Rendering.LocalKeyword) },
            { 64, typeof(global::UnityEngine.Rendering.ReflectionProbeBlendInfo) },
            { 65, typeof(global::UnityEngine.Rendering.RenderTargetBinding) },
            { 66, typeof(global::UnityEngine.Experimental.Rendering.RayTracingAccelerationStructure) },
            { 67, typeof(global::UnityEngine.Experimental.Rendering.RayTracingShader) },
            { 68, typeof(global::UnityEngine.EventSystems.UIBehaviour) },
            { 69, typeof(global::UnityEngine.Audio.AudioMixer) },
            { 70, typeof(global::UnityEngine.Audio.AudioMixerGroup) },
            { 71, typeof(global::UnityEngine.Audio.AudioMixerSnapshot) },
            { 72, typeof(global::UnityEngine.AI.NavMeshAgent) },
            { 73, typeof(global::UnityEngine.AI.NavMesh) },
            { 74, typeof(global::UnityEngine.AI.NavMeshBuilder) },
            { 75, typeof(global::UnityEngine.AI.NavMeshData) },
            { 76, typeof(global::UnityEngine.AI.NavMeshObstacle) },
            { 77, typeof(global::UnityEngine.AI.NavMeshPath) },
            { 78, typeof(global::UnityEngine.AI.NavMeshQueryFilter) },
            { 79, typeof(global::UnityEngine.AI.NavMeshTriangulation) },
            { 80, typeof(global::UnityEngine.AI.OffMeshLink) },
            { 81, typeof(global::TMPro.TMP_Style) },
            { 82, typeof(global::TMPro.TMP_Text) },
            { 83, typeof(global::TMPro.TextMeshProUGUI) },
            { 84, typeof(global::UnityEngine.TextAsset) },
			#endregion IdToType
		};

		private static readonly Dictionary<Type, int> TypeToId = new()
		{
			#region TypeToId
            { typeof(global::UnityEngine.Object), 0 },
            { typeof(global::UnityEngine.AnimationClip), 1 },
            { typeof(global::UnityEngine.AnimationCurve), 2 },
            { typeof(global::UnityEngine.Animator), 3 },
            { typeof(global::UnityEngine.AnimatorControllerParameter), 4 },
            { typeof(global::UnityEngine.ArticulationBody), 5 },
            { typeof(global::UnityEngine.ArticulationJacobian), 6 },
            { typeof(global::UnityEngine.AudioBehaviour), 7 },
            { typeof(global::UnityEngine.AudioClip), 8 },
            { typeof(global::UnityEngine.AudioListener), 9 },
            { typeof(global::UnityEngine.AudioSource), 10 },
            { typeof(global::UnityEngine.Avatar), 11 },
            { typeof(global::UnityEngine.Behaviour), 12 },
            { typeof(global::UnityEngine.BoxCollider), 13 },
            { typeof(global::UnityEngine.Camera.CameraCallback), 14 },
            { typeof(global::UnityEngine.Camera), 15 },
            { typeof(global::UnityEngine.CapsuleCollider), 16 },
            { typeof(global::UnityEngine.Collider), 17 },
            { typeof(global::UnityEngine.Collision), 18 },
            { typeof(global::UnityEngine.Component), 19 },
            { typeof(global::UnityEngine.ComputeBuffer), 20 },
            { typeof(global::UnityEngine.ComputeShader), 21 },
            { typeof(global::UnityEngine.Coroutine), 22 },
            { typeof(global::UnityEngine.Cubemap), 23 },
            { typeof(global::UnityEngine.Debug), 24 },
            { typeof(global::UnityEngine.GameObject), 25 },
            { typeof(global::UnityEngine.Graphics), 26 },
            { typeof(global::UnityEngine.GraphicsBuffer), 27 },
            { typeof(global::UnityEngine.HumanBone), 28 },
            { typeof(global::UnityEngine.HumanDescription), 29 },
            { typeof(global::UnityEngine.Input), 30 },
            { typeof(global::UnityEngine.LightProbeProxyVolume), 31 },
            { typeof(global::UnityEngine.Material), 32 },
            { typeof(global::UnityEngine.MaterialPropertyBlock), 33 },
            { typeof(global::UnityEngine.Mesh), 34 },
            { typeof(global::UnityEngine.MeshCollider), 35 },
            { typeof(global::UnityEngine.MeshFilter), 36 },
            { typeof(global::UnityEngine.MeshRenderer), 37 },
            { typeof(global::UnityEngine.MonoBehaviour), 38 },
            { typeof(global::UnityEngine.Motion), 39 },
            { typeof(global::UnityEngine.PhysicMaterial), 40 },
            { typeof(global::UnityEngine.Physics), 41 },
            { typeof(global::UnityEngine.RectTransform), 42 },
            { typeof(global::UnityEngine.ReflectionProbe), 43 },
            { typeof(global::UnityEngine.Renderer), 44 },
            { typeof(global::UnityEngine.RenderParams), 45 },
            { typeof(global::UnityEngine.RenderTargetSetup), 46 },
            { typeof(global::UnityEngine.RenderTexture), 47 },
            { typeof(global::UnityEngine.Rigidbody), 48 },
            { typeof(global::UnityEngine.RuntimeAnimatorController), 49 },
            { typeof(global::UnityEngine.Shader), 50 },
            { typeof(global::UnityEngine.SkeletonBone), 51 },
            { typeof(global::UnityEngine.SkinnedMeshRenderer), 52 },
            { typeof(global::UnityEngine.SphereCollider), 53 },
            { typeof(global::UnityEngine.Texture2D), 54 },
            { typeof(global::UnityEngine.Texture), 55 },
            { typeof(global::UnityEngine.Time), 56 },
            { typeof(global::UnityEngine.Transform), 57 },
            { typeof(global::UnityEngine.YieldInstruction), 58 },
            { typeof(global::UnityEngine.UI.Graphic), 59 },
            { typeof(global::UnityEngine.UI.MaskableGraphic), 60 },
            { typeof(global::UnityEngine.Rendering.CommandBuffer), 61 },
            { typeof(global::UnityEngine.Rendering.GlobalKeyword), 62 },
            { typeof(global::UnityEngine.Rendering.LocalKeyword), 63 },
            { typeof(global::UnityEngine.Rendering.ReflectionProbeBlendInfo), 64 },
            { typeof(global::UnityEngine.Rendering.RenderTargetBinding), 65 },
            { typeof(global::UnityEngine.Experimental.Rendering.RayTracingAccelerationStructure), 66 },
            { typeof(global::UnityEngine.Experimental.Rendering.RayTracingShader), 67 },
            { typeof(global::UnityEngine.EventSystems.UIBehaviour), 68 },
            { typeof(global::UnityEngine.Audio.AudioMixer), 69 },
            { typeof(global::UnityEngine.Audio.AudioMixerGroup), 70 },
            { typeof(global::UnityEngine.Audio.AudioMixerSnapshot), 71 },
            { typeof(global::UnityEngine.AI.NavMeshAgent), 72 },
            { typeof(global::UnityEngine.AI.NavMesh), 73 },
            { typeof(global::UnityEngine.AI.NavMeshBuilder), 74 },
            { typeof(global::UnityEngine.AI.NavMeshData), 75 },
            { typeof(global::UnityEngine.AI.NavMeshObstacle), 76 },
            { typeof(global::UnityEngine.AI.NavMeshPath), 77 },
            { typeof(global::UnityEngine.AI.NavMeshQueryFilter), 78 },
            { typeof(global::UnityEngine.AI.NavMeshTriangulation), 79 },
            { typeof(global::UnityEngine.AI.OffMeshLink), 80 },
            { typeof(global::TMPro.TMP_Style), 81 },
            { typeof(global::TMPro.TMP_Text), 82 },
            { typeof(global::TMPro.TextMeshProUGUI), 83 },
            { typeof(global::UnityEngine.TextAsset), 84 },
			#endregion TypeToId
		};

		public static Type GetType(int id) => IdToType.GetValueOrDefault(id, typeof(global::UnityEngine.Object));

		public static int GetId(Type type) => TypeToId.GetValueOrDefault(type, 0);
	}
}